### ISSUE TITLE
你好，请问下输入完有回调监听到吗

### ISSUE THREAD

**Issue by simpleLiYu** [LiuSky/CodeTextField#1]

**Comment by LiuSky** [comment]
新增了回调，请下载看下Demo

**Comment by simpleLiYu** [comment]
你好，我想明文改成密文显示可以设置吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuSky/CodeTextField"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 上午9:44
收件人:&nbsp;"LiuSky/CodeTextField"<CodeTextField@noreply.github.com&gt;;
抄送:&nbsp;"时间。回不去了"<792115885@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [LiuSky/CodeTextField] 你好，请问下输入完有回调监听到吗 (#1)





 
新增了回调，请下载看下Demo

**Comment by LiuSky** [comment]
可以的。你可以自定义LableRenderable
