### ISSUE TITLE
怎么改变字体大小呢

### ISSUE THREAD

**Issue by slnBaby** [LiuSky/CodeTextField#2]

**Comment by LiuSky** [comment]
<img width="397" alt="截屏2020-10-30 上午8 48 50" src="https://user-images.githubusercontent.com/3087745/97647330-ebdffa00-1a8c-11eb-9bf2-9494eba616a2.png">
自定义标签上面可以任意自己设置大小。
<img width="1148" alt="截屏2020-10-30 上午8 48 54" src="https://user-images.githubusercontent.com/3087745/97647293-d4a10c80-1a8c-11eb-8f55-ab0dc3384a49.png">
