### ISSUE TITLE
如何隐藏_UICursorAccessoryHostView

### ISSUE THREAD

**Issue by woaiyouxi0803** [LiuSky/CodeTextField#4]
![截屏2024-11-29 18 22 02](https://github.com/user-attachments/assets/d351b269-99e8-4313-8511-6666de0f690d)
_UICursorAccessoryHostView不想显示

**Comment by LiuSky** [comment]
可以尝试下    public override func addSubview(_ view: UIView) {
            if NSStringFromClass(type(of: view)).contains("_UICursorAccessoryHostView") {
                return
            }
            super.addSubview(view)
        }
    帮忙验证下。如果可以的话，提个pr给我。我合并
